NEST_STATE = 1
REWARD_STATE = 2
DETECT_STATE = 3
RETREAT_STATE = 4
DEAD_STATE = 5
CAUTIOUS_REWARD_STATE = 6
CAUTIOUS_DETECT_STATE = 7
INVALID_STATE = 8
DYING_STATE = 9

STAY_ACTION = 1
LEAVE_ACTION = 2
LEAVE_CAUTIOUS_ACTION = 3